version: '3.3'

services:
  webservice:
    image: ctelfer/apache-rolling-update:latest
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1s
      timeout: 10s
      retries: 3
    stop_grace_period: 1h
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
